# Mount

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd /content/drive/MyDrive/CS269_Climate_Project

/content/drive/MyDrive/CS269_Climate_Project

In [2]:
import pandas as pd
import numpy as np

# El Nino Dataset

Text files from https://psl.noaa.gov/enso/data.html climate indices, convert to csv and create memmap from El Nino data by repeating the index across time and long/lat

In [ ]:
file_path = 'Datasets/elnino34.txt'

with open(file_path, 'r') as file:
    lines = file.readlines()

data = []
for line in lines:
    values = line.split()
    year = int(values[0])
    monthly_values = [float(value) for value in values[1:]]
    row = [year] + monthly_values
    data.append(row)

columns = ['Year', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
nino_df = pd.DataFrame(data, columns=columns)

In [ ]:
start_date = '1870-01-01 00:00:00'
end_date = '2023-12-31 23:59:59'
date_range = pd.date_range(start=start_date, end=end_date, freq='H')
hourly_df = pd.DataFrame(index=date_range)
hourly_df['Year'] = hourly_df.index.year
hourly_df['Month'] = hourly_df.index.month

month_num_to_name = {1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun',
                     7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dec'}

def get_monthly_value(row):
    year = row['Year']
    month = month_num_to_name[row['Month']]
    return nino_df.loc[nino_df['Year'] == year, month].values[0]

hourly_df['Value'] = hourly_df.apply(get_monthly_value, axis=1)
hourly_df = hourly_df.drop(['Year', 'Month'], axis=1)

csv_file_path = 'hourly_elnino_XX.csv'
hourly_df.to_csv(csv_file_path)

After running above for all 4 nino indices, combine them together into a memmap, indexes represent from 1979 to 2019

In [ ]:
from tqdm import tqdm

nino_df = pd.read_csv('hourly_elnino_34.csv')
hour_data = df.iloc[955464:1314864]['Value'].to_numpy()

x1 = [np.full((1,5,12), i) for i in tqdm(hour_data)]
y1 = np.array(x1)

df = pd.read_csv('hourly_elnino_12.csv')
hour_data = df.iloc[955464:1314864]['Value'].to_numpy()

x2 = [np.full((1,5,12), i) for i in tqdm(hour_data)]
y2 = np.array(x2)

df = pd.read_csv('hourly_elnino_3.csv')
hour_data = df.iloc[955464:1314864]['Value'].to_numpy()

x3 = [np.full((1,5,12), i) for i in tqdm(hour_data)]
y3 = np.array(x3)

df = pd.read_csv('hourly_elnino_4.csv')
hour_data = df.iloc[955464:1314864]['Value'].to_numpy()

x4 = [np.full((1,5,12), i) for i in tqdm(hour_data)]
y4 = np.array(x4)

print(y1.mean(), y1.std())
print(y2.mean(), y2.std())
print(y3.mean(), y3.std())
print(y4.mean(), y4.std())


hourly_data_memmap = np.memmap('ninoXX_5625.mmap', dtype='float32', mode='w+', shape=(359400, 4, 5, 12))
hourly_data_memmap[:,0:,:,:] = y1
hourly_data_memmap[:,1:,:,:] = y2
hourly_data_memmap[:,2:,:,:] = y3
hourly_data_memmap[:,3:,:,:] = y4

# Read in Storm Events Data

The links on their website are constantly updated, since they include their update date, meaning file_names may need to be updated

In [ ]:
import requests
from io import BytesIO
import gzip
base_url = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/"
def download_and_import_csv(file_name):
    file_url = base_url + file_name
    try:
        response = requests.get(file_url)
        response.raise_for_status()  # will raise an HTTPError if the HTTP request returned an unsuccessful status code
        with gzip.open(BytesIO(response.content)) as f:
            df = pd.read_csv(f)
        return df
    except requests.HTTPError as e:
        print(f"Error downloading {file_name}: {e}")
        return None  # Return None if there's an error
# Update this list based on the file names you have
file_names = [
    'StormEvents_details-ftp_v1.0_d1979_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1980_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1981_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1982_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1983_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1984_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1985_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1986_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1987_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1988_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1989_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1990_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1991_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1992_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1993_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1994_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1995_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1996_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1997_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1998_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d1999_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2000_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2001_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2002_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2003_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2004_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2005_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2006_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2007_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2008_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2009_c20231116.csv.gz',
    'StormEvents_details-ftp_v1.0_d2010_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2011_c20230417.csv.gz',
    'StormEvents_details-ftp_v1.0_d2012_c20221216.csv.gz',
    'StormEvents_details-ftp_v1.0_d2013_c20230118.csv.gz',
    'StormEvents_details-ftp_v1.0_d2014_c20231116.csv.gz',
    'StormEvents_details-ftp_v1.0_d2015_c20220425.csv.gz',
    'StormEvents_details-ftp_v1.0_d2016_c20220719.csv.gz',
    'StormEvents_details-ftp_v1.0_d2017_c20230317.csv.gz',
    'StormEvents_details-ftp_v1.0_d2018_c20230616.csv.gz',
    'StormEvents_details-ftp_v1.0_d2019_c20231017.csv.gz',
]
all_dataframes = []
for file_name in file_names:
    df = download_and_import_csv(file_name)
    if df is not None:
        all_dataframes.append(df)
# Concatenate all dataframes into one
combined_df = pd.concat(all_dataframes, ignore_index=True)
df_all = combined_df

In [ ]:
df_all.to_csv('Datasets/storm_data_1979_2023.csv')

Read in data via csv that we converted to

In [ ]:
df_all = pd.read_csv('Datasets/storm_data_1979_2023.csv')

# Data Exploration

Find missing values

In [5]:
missing_counts_per_year = df_all.groupby('YEAR').apply(lambda group: group[['BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON']].isna().sum())

In [6]:
missing_counts_per_year

      BEGIN_LAT  BEGIN_LON  END_LAT  END_LON
YEAR
1979          0          1     4033     4033
1980          0          0     5791     5791
1981          0          0     4290     4290
1982          0          0     6728     6728
1983          0          0     8037     8037
1984          0          0     6984     6984
1985          0          0     7712     7712
1986          0          0     8417     8417
1987          0          0     7198     7198
1988          0          0     7023     7023
1989          0          0    10119    10119
1990          0          0    10529    10529
1991          0          0    12234    12234
1992          0          0    13166    13166
1993       8239       8239     8553     8553
1994      15045      15045    15532    15532
1995      19714      19714    20314    20314
1996      26661      26661    26661    26661
1997      22394      22394    22394    22394
1998      23346      23346    23346    23346
1999      24412      24412    24412    24412
2000      27687      27689    27687    27689
2001      23575      23578    23575    23578
2002      24414      24414    24414    24414
2003      25559      25559    25559    25559
2004      25421      25423    25421    25423
2005      20963      20963    20963    20963
2006      22575      22575    22575    22575
2007      23288      23288    23288    23288
2008      24366      24366    24366    24366
2009      19825      19825    19825    19825
2010      23968      23968    23968    23968
2011      26884      26884    26884    26884
2012      26417      26417    26417    26417
2013      24425      24425    24425    24425
2014      25153      25153    25153    25153
2015      20619      20619    20619    20619
2016      19556      19556    19556    19556
2017      17659      17659    17659    17659
2018      24593      24593    24593    24593
2019      24348      24348    24348    24348

Find count of severe storms per year, can see that the number of storms gradually increases so many storms in the past were not recorded, a good cutoff point we found was year 2000

In [7]:
df_all['YEAR'].value_counts().sort_index()

1979     4279
1980     6136
1981     4517
1982     7126
1983     8322
1984     7335
1985     7979
1986     8725
1987     7363
1988     7257
1989    10407
1990    10945
1991    12516
1992    13534
1993     8664
1994    15627
1995    20465
1996    48561
1997    41991
1998    50973
1999    46383
2000    52007
2001    48875
2002    50936
2003    52956
2004    52409
2005    53976
2006    56400
2007    59010
2008    71190
2009    57398
2010    62807
2011    79091
2012    64503
2013    59986
2014    59475
2015    57906
2016    56005
2017    57029
2018    62697
2019    67861
Name: YEAR, dtype: int64

Drop NA

In [8]:
df = df_all.dropna(subset=['BEGIN_LAT', 'BEGIN_LON'])

# Experiment 3

Filter by floods

In [4]:
df_flood = df_all[(df_all['EVENT_TYPE'] == 'Flash Flood') | (df_all['EVENT_TYPE'] == 'Flood')]

In [ ]:
df_all = df_flood

# Data Processing

Capture the latitude and longitude over the contiguous US and convert it to an index using 5.625 degrees and take relevant columns

In [ ]:
us_filtered_df = df[
    (df['BEGIN_LAT'] >= 22.5) & (df['BEGIN_LAT'] <= 50.625) &
    (df['BEGIN_LON'] <= -61.875) & (df['BEGIN_LON'] >= -129.375)
]

us_filtered_df['LAT'] = us_filtered_df['BEGIN_LAT'].apply(lambda x : (x - 22.5)//5.625)
us_filtered_df['LON'] = us_filtered_df['BEGIN_LON'].apply(lambda x : -(x + 61.875)//5.625)

In [27]:
us_filtered_df = us_filtered_df[['BEGIN_YEARMONTH', 'BEGIN_DAY', 'BEGIN_TIME',
                                 'END_DAY', 'END_TIME', 'END_YEARMONTH', 'LAT', 'LON']]

# Experiment 2 & 3

For experiments 2 & 3, filter out severe storms before the year 2000, due to missingness in years before

In [28]:
us_filtered_df = us_filtered_df[us_filtered_df['BEGIN_YEARMONTH'].apply(lambda x : int(x)) >= 200001]

Note: there are storms after 03-2019, they are just out of order

In [29]:
us_filtered_df

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_DAY,END_TIME,END_YEARMONTH,LAT,LON
349109,200008,3,1410,3,1410,200008,1.0,4.0
349110,200008,9,1405,9,1405,200008,1.0,4.0
349111,200008,9,1615,9,1615,200008,1.0,4.0
349124,200002,13,2310,13,2310,200002,2.0,3.0
349125,200002,13,2315,13,2315,200002,2.0,3.0
...,...,...,...,...,...,...,...,...
1531617,201903,3,1913,3,1916,201903,2.0,3.0
1531618,201903,3,1853,3,1906,201903,2.0,3.0
1531619,201903,3,1913,3,1916,201903,2.0,3.0
1531620,201903,3,1933,3,1935,201903,2.0,3.0
1531621,201903,1,1915,1,1915,201903,2.0,3.0

Convert time-related columns to datetime object

In [30]:
us_filtered_df['BEGIN_YEARMONTH'] = us_filtered_df['BEGIN_YEARMONTH'].astype(str)
us_filtered_df['BEGIN_DAY'] = us_filtered_df['BEGIN_DAY'].apply(lambda x: f"{x:02d}")
us_filtered_df['BEGIN_TIME'] = us_filtered_df['BEGIN_TIME'].apply(lambda x: f"{x:04d}")
us_filtered_df['DATETIME'] = us_filtered_df['BEGIN_YEARMONTH'] + us_filtered_df['BEGIN_DAY'] + us_filtered_df['BEGIN_TIME'].apply(lambda x: x[:2]+"00")
us_filtered_df['DATETIME'] = pd.to_datetime(us_filtered_df['DATETIME'], format='%Y%m%d%H%M')

In [31]:
us_filtered_df['END_YEARMONTH'] = us_filtered_df['END_YEARMONTH'].astype(str)
us_filtered_df['END_DAY'] = us_filtered_df['END_DAY'].apply(lambda x: f"{x:02d}")
us_filtered_df['END_TIME'] = us_filtered_df['END_TIME'].apply(lambda x: f"{x:04d}")
us_filtered_df['END_DATETIME'] = us_filtered_df['END_YEARMONTH'] + us_filtered_df['END_DAY'] + us_filtered_df['END_TIME'].apply(lambda x: x[:2]+"00")
us_filtered_df['END_DATETIME'] = pd.to_datetime(us_filtered_df['END_DATETIME'], format='%Y%m%d%H%M')

Create a dictionary mapping datetime to index, one for 1979 start, and another for 2000 start (Experiment 2&3)

In [22]:
start_date = '1979-01-01 00:00:00'
end_date = '2023-12-31 23:59:59'

date_range = pd.date_range(start=start_date, end=end_date, freq='H')
datetime_dict = dict(zip(date_range.strftime('%Y-%m-%d %H:%M:%S'), np.arange(359400)))

In [24]:
start_date = '2000-01-01 00:00:00'
end_date = '2023-12-31 23:59:59'

date_range = pd.date_range(start=start_date, end=end_date, freq='H')
datetime_dict = dict(zip(date_range.strftime('%Y-%m-%d %H:%M:%S'), np.arange(175320)))

In [25]:
datetime_dict

{'2000-01-01 00:00:00': 0,
 '2000-01-01 01:00:00': 1,
 '2000-01-01 02:00:00': 2,
 '2000-01-01 03:00:00': 3,
 '2000-01-01 04:00:00': 4,
 '2000-01-01 05:00:00': 5,
 '2000-01-01 06:00:00': 6,
 '2000-01-01 07:00:00': 7,
 '2000-01-01 08:00:00': 8,
 '2000-01-01 09:00:00': 9,
 '2000-01-01 10:00:00': 10,
 '2000-01-01 11:00:00': 11,
 '2000-01-01 12:00:00': 12,
 '2000-01-01 13:00:00': 13,
 '2000-01-01 14:00:00': 14,
 '2000-01-01 15:00:00': 15,
 '2000-01-01 16:00:00': 16,
 '2000-01-01 17:00:00': 17,
 '2000-01-01 18:00:00': 18,
 '2000-01-01 19:00:00': 19,
 '2000-01-01 20:00:00': 20,
 '2000-01-01 21:00:00': 21,
 '2000-01-01 22:00:00': 22,
 '2000-01-01 23:00:00': 23,
 '2000-01-02 00:00:00': 24,
 '2000-01-02 01:00:00': 25,
 '2000-01-02 02:00:00': 26,
 '2000-01-02 03:00:00': 27,
 '2000-01-02 04:00:00': 28,
 '2000-01-02 05:00:00': 29,
 '2000-01-02 06:00:00': 30,
 '2000-01-02 07:00:00': 31,
 '2000-01-02 08:00:00': 32,
 '2000-01-02 09:00:00': 33,
 '2000-01-02 10:00:00': 34,
 '2000-01-02 11:00:00': 35,
 '2000-01-02 12:00:00': 36,
 '2000-01-02 13:00:00': 37,
 '2000-01-02 14:00:00': 38,
 '2000-01-02 15:00:00': 39,
 '2000-01-02 16:00:00': 40,
 '2000-01-02 17:00:00': 41,
 '2000-01-02 18:00:00': 42,
 '2000-01-02 19:00:00': 43,
 '2000-01-02 20:00:00': 44,
 '2000-01-02 21:00:00': 45,
 '2000-01-02 22:00:00': 46,
 '2000-01-02 23:00:00': 47,
 '2000-01-03 00:00:00': 48,
 '2000-01-03 01:00:00': 49,
 '2000-01-03 02:00:00': 50,
 '2000-01-03 03:00:00': 51,
 '2000-01-03 04:00:00': 52,
 '2000-01-03 05:00:00': 53,
 '2000-01-03 06:00:00': 54,
 '2000-01-03 07:00:00': 55,
 '2000-01-03 08:00:00': 56,
 '2000-01-03 09:00:00': 57,
 '2000-01-03 10:00:00': 58,
 '2000-01-03 11:00:00': 59,
 '2000-01-03 12:00:00': 60,
 '2000-01-03 13:00:00': 61,
 '2000-01-03 14:00:00': 62,
 '2000-01-03 15:00:00': 63,
 '2000-01-03 16:00:00': 64,
 '2000-01-03 17:00:00': 65,
 '2000-01-03 18:00:00': 66,
 '2000-01-03 19:00:00': 67,
 '2000-01-03 20:00:00': 68,
 '2000-01-03 21:00:00': 69,
 '2000-01-03 22:00:00': 70,
 '2000-01-03 23:00:00': 71,
 '2000-01-04 00:00:00': 72,
 '2000-01-04 01:00:00': 73,
 '2000-01-04 02:00:00': 74,
 '2000-01-04 03:00:00': 75,
 '2000-01-04 04:00:00': 76,
 '2000-01-04 05:00:00': 77,
 '2000-01-04 06:00:00': 78,
 '2000-01-04 07:00:00': 79,
 '2000-01-04 08:00:00': 80,
 '2000-01-04 09:00:00': 81,
 '2000-01-04 10:00:00': 82,
 '2000-01-04 11:00:00': 83,
 '2000-01-04 12:00:00': 84,
 '2000-01-04 13:00:00': 85,
 '2000-01-04 14:00:00': 86,
 '2000-01-04 15:00:00': 87,
 '2000-01-04 16:00:00': 88,
 '2000-01-04 17:00:00': 89,
 '2000-01-04 18:00:00': 90,
 '2000-01-04 19:00:00': 91,
 '2000-01-04 20:00:00': 92,
 '2000-01-04 21:00:00': 93,
 '2000-01-04 22:00:00': 94,
 '2000-01-04 23:00:00': 95,
 '2000-01-05 00:00:00': 96,
 '2000-01-05 01:00:00': 97,
 '2000-01-05 02:00:00': 98,
 '2000-01-05 03:00:00': 99,
 '2000-01-05 04:00:00': 100,
 '2000-01-05 05:00:00': 101,
 '2000-01-05 06:00:00': 102,
 '2000-01-05 07:00:00': 103,
 '2000-01-05 08:00:00': 104,
 '2000-01-05 09:00:00': 105,
 '2000-01-05 10:00:00': 106,
 '2000-01-05 11:00:00': 107,
 '2000-01-05 12:00:00': 108,
 '2000-01-05 13:00:00': 109,
 '2000-01-05 14:00:00': 110,
 '2000-01-05 15:00:00': 111,
 '2000-01-05 16:00:00': 112,
 '2000-01-05 17:00:00': 113,
 '2000-01-05 18:00:00': 114,
 '2000-01-05 19:00:00': 115,
 '2000-01-05 20:00:00': 116,
 '2000-01-05 21:00:00': 117,
 '2000-01-05 22:00:00': 118,
 '2000-01-05 23:00:00': 119,
 '2000-01-06 00:00:00': 120,
 '2000-01-06 01:00:00': 121,
 '2000-01-06 02:00:00': 122,
 '2000-01-06 03:00:00': 123,
 '2000-01-06 04:00:00': 124,
 '2000-01-06 05:00:00': 125,
 '2000-01-06 06:00:00': 126,
 '2000-01-06 07:00:00': 127,
 '2000-01-06 08:00:00': 128,
 '2000-01-06 09:00:00': 129,
 '2000-01-06 10:00:00': 130,
 '2000-01-06 11:00:00': 131,
 '2000-01-06 12:00:00': 132,
 '2000-01-06 13:00:00': 133,
 '2000-01-06 14:00:00': 134,
 '2000-01-06 15:00:00': 135,
 '2000-01-06 16:00:00': 136,
 '2000-01-06 17:00:00': 137,
 '2000-01-06 18:00:00': 138,
 '2000-01-06 19:00:00': 139,
 '2000-01-06 20:00:00': 140,
 '2000-01-06 21:00:00': 141,
 '2000-01-06 22:00:00': 142,
 '2000-01-06 23:00:00': 143,
 '2000-01-07 00:00:00': 144,
 '2000-01-07 01:00:00': 145,
 '2000-01-07 02:00:00': 146,
 '2000-01-07 03:00:00': 147,
 '2000-01-07 04:00:00': 148,
 '2000-01-07 05:00:00': 149,
 '2000-01-07 06:00:00': 150,
 '2000-01-07 07:00:00': 151,
 '2000-01-07 08:00:00': 152,
 '2000-01-07 09:00:00': 153,
 '2000-01-07 10:00:00': 154,
 '2000-01-07 11:00:00': 155,
 '2000-01-07 12:00:00': 156,
 '2000-01-07 13:00:00': 157,
 '2000-01-07 14:00:00': 158,
 '2000-01-07 15:00:00': 159,
 '2000-01-07 16:00:00': 160,
 '2000-01-07 17:00:00': 161,
 '2000-01-07 18:00:00': 162,
 '2000-01-07 19:00:00': 163,
 '2000-01-07 20:00:00': 164,
 '2000-01-07 21:00:00': 165,
 '2000-01-07 22:00:00': 166,
 '2000-01-07 23:00:00': 167,
 '2000-01-08 00:00:00': 168,
 '2000-01-08 01:00:00': 169,
 '2000-01-08 02:00:00': 170,
 '2000-01-08 03:00:00': 171,
 '2000-01-08 04:00:00': 172,
 '2000-01-08 05:00:00': 173,
 '2000-01-08 06:00:00': 174,
 '2000-01-08 07:00:00': 175,
 '2000-01-08 08:00:00': 176,
 '2000-01-08 09:00:00': 177,
 '2000-01-08 10:00:00': 178,
 '2000-01-08 11:00:00': 179,
 '2000-01-08 12:00:00': 180,
 '2000-01-08 13:00:00': 181,
 '2000-01-08 14:00:00': 182,
 '2000-01-08 15:00:00': 183,
 '2000-01-08 16:00:00': 184,
 '2000-01-08 17:00:00': 185,
 '2000-01-08 18:00:00': 186,
 '2000-01-08 19:00:00': 187,
 '2000-01-08 20:00:00': 188,
 '2000-01-08 21:00:00': 189,
 '2000-01-08 22:00:00': 190,
 '2000-01-08 23:00:00': 191,
 '2000-01-09 00:00:00': 192,
 '2000-01-09 01:00:00': 193,
 '2000-01-09 02:00:00': 194,
 '2000-01-09 03:00:00': 195,
 '2000-01-09 04:00:00': 196,
 '2000-01-09 05:00:00': 197,
 '2000-01-09 06:00:00': 198,
 '2000-01-09 07:00:00': 199,
 '2000-01-09 08:00:00': 200,
 '2000-01-09 09:00:00': 201,
 '2000-01-09 10:00:00': 202,
 '2000-01-09 11:00:00': 203,
 '2000-01-09 12:00:00': 204,
 '2000-01-09 13:00:00': 205,
 '2000-01-09 14:00:00': 206,
 '2000-01-09 15:00:00': 207,
 '2000-01-09 16:00:00': 208,
 '2000-01-09 17:00:00': 209,
 '2000-01-09 18:00:00': 210,
 '2000-01-09 19:00:00': 211,
 '2000-01-09 20:00:00': 212,
 '2000-01-09 21:00:00': 213,
 '2000-01-09 22:00:00': 214,
 '2000-01-09 23:00:00': 215,
 '2000-01-10 00:00:00': 216,
 '2000-01-10 01:00:00': 217,
 '2000-01-10 02:00:00': 218,
 '2000-01-10 03:00:00': 219,
 '2000-01-10 04:00:00': 220,
 '2000-01-10 05:00:00': 221,
 '2000-01-10 06:00:00': 222,
 '2000-01-10 07:00:00': 223,
 '2000-01-10 08:00:00': 224,
 '2000-01-10 09:00:00': 225,
 '2000-01-10 10:00:00': 226,
 '2000-01-10 11:00:00': 227,
 '2000-01-10 12:00:00': 228,
 '2000-01-10 13:00:00': 229,
 '2000-01-10 14:00:00': 230,
 '2000-01-10 15:00:00': 231,
 '2000-01-10 16:00:00': 232,
 '2000-01-10 17:00:00': 233,
 '2000-01-10 18:00:00': 234,
 '2000-01-10 19:00:00': 235,
 '2000-01-10 20:00:00': 236,
 '2000-01-10 21:00:00': 237,
 '2000-01-10 22:00:00': 238,
 '2000-01-10 23:00:00': 239,
 '2000-01-11 00:00:00': 240,
 '2000-01-11 01:00:00': 241,
 '2000-01-11 02:00:00': 242,
 '2000-01-11 03:00:00': 243,
 '2000-01-11 04:00:00': 244,
 '2000-01-11 05:00:00': 245,
 '2000-01-11 06:00:00': 246,
 '2000-01-11 07:00:00': 247,
 '2000-01-11 08:00:00': 248,
 '2000-01-11 09:00:00': 249,
 '2000-01-11 10:00:00': 250,
 '2000-01-11 11:00:00': 251,
 '2000-01-11 12:00:00': 252,
 '2000-01-11 13:00:00': 253,
 '2000-01-11 14:00:00': 254,
 '2000-01-11 15:00:00': 255,
 '2000-01-11 16:00:00': 256,
 '2000-01-11 17:00:00': 257,
 '2000-01-11 18:00:00': 258,
 '2000-01-11 19:00:00': 259,
 '2000-01-11 20:00:00': 260,
 '2000-01-11 21:00:00': 261,
 '2000-01-11 22:00:00': 262,
 '2000-01-11 23:00:00': 263,
 '2000-01-12 00:00:00': 264,
 '2000-01-12 01:00:00': 265,
 '2000-01-12 02:00:00': 266,
 '2000-01-12 03:00:00': 267,
 '2000-01-12 04:00:00': 268,
 '2000-01-12 05:00:00': 269,
 '2000-01-12 06:00:00': 270,
 '2000-01-12 07:00:00': 271,
 '2000-01-12 08:00:00': 272,
 '2000-01-12 09:00:00': 273,
 '2000-01-12 10:00:00': 274,
 '2000-01-12 11:00:00': 275,
 '2000-01-12 12:00:00': 276,
 '2000-01-12 13:00:00': 277,
 '2000-01-12 14:00:00': 278,
 '2000-01-12 15:00:00': 279,
 '2000-01-12 16:00:00': 280,
 '2000-01-12 17:00:00': 281,
 '2000-01-12 18:00:00': 282,
 '2000-01-12 19:00:00': 283,
 '2000-01-12 20:00:00': 284,
 '2000-01-12 21:00:00': 285,
 '2000-01-12 22:00:00': 286,
 '2000-01-12 23:00:00': 287,
 '2000-01-13 00:00:00': 288,
 '2000-01-13 01:00:00': 289,
 '2000-01-13 02:00:00': 290,
 '2000-01-13 03:00:00': 291,
 '2000-01-13 04:00:00': 292,
 '2000-01-13 05:00:00': 293,
 '2000-01-13 06:00:00': 294,
 '2000-01-13 07:00:00': 295,
 '2000-01-13 08:00:00': 296,
 '2000-01-13 09:00:00': 297,
 '2000-01-13 10:00:00': 298,
 '2000-01-13 11:00:00': 299,
 '2000-01-13 12:00:00': 300,
 '2000-01-13 13:00:00': 301,
 '2000-01-13 14:00:00': 302,
 '2000-01-13 15:00:00': 303,
 '2000-01-13 16:00:00': 304,
 '2000-01-13 17:00:00': 305,
 '2000-01-13 18:00:00': 306,
 '2000-01-13 19:00:00': 307,
 '2000-01-13 20:00:00': 308,
 '2000-01-13 21:00:00': 309,
 '2000-01-13 22:00:00': 310,
 '2000-01-13 23:00:00': 311,
 '2000-01-14 00:00:00': 312,
 '2000-01-14 01:00:00': 313,
 '2000-01-14 02:00:00': 314,
 '2000-01-14 03:00:00': 315,
 '2000-01-14 04:00:00': 316,
 '2000-01-14 05:00:00': 317,
 '2000-01-14 06:00:00': 318,
 '2000-01-14 07:00:00': 319,
 '2000-01-14 08:00:00': 320,
 '2000-01-14 09:00:00': 321,
 '2000-01-14 10:00:00': 322,
 '2000-01-14 11:00:00': 323,
 '2000-01-14 12:00:00': 324,
 '2000-01-14 13:00:00': 325,
 '2000-01-14 14:00:00': 326,
 '2000-01-14 15:00:00': 327,
 '2000-01-14 16:00:00': 328,
 '2000-01-14 17:00:00': 329,
 '2000-01-14 18:00:00': 330,
 '2000-01-14 19:00:00': 331,
 '2000-01-14 20:00:00': 332,
 '2000-01-14 21:00:00': 333,
 '2000-01-14 22:00:00': 334,
 '2000-01-14 23:00:00': 335,
 '2000-01-15 00:00:00': 336,
 '2000-01-15 01:00:00': 337,
 '2000-01-15 02:00:00': 338,
 '2000-01-15 03:00:00': 339,
 '2000-01-15 04:00:00': 340,
 '2000-01-15 05:00:00': 341,
 '2000-01-15 06:00:00': 342,
 '2000-01-15 07:00:00': 343,
 '2000-01-15 08:00:00': 344,
 '2000-01-15 09:00:00': 345,
 '2000-01-15 10:00:00': 346,
 '2000-01-15 11:00:00': 347,
 '2000-01-15 12:00:00': 348,
 '2000-01-15 13:00:00': 349,
 '2000-01-15 14:00:00': 350,
 '2000-01-15 15:00:00': 351,
 '2000-01-15 16:00:00': 352,
 '2000-01-15 17:00:00': 353,
 '2000-01-15 18:00:00': 354,
 '2000-01-15 19:00:00': 355,
 '2000-01-15 20:00:00': 356,
 '2000-01-15 21:00:00': 357,
 '2000-01-15 22:00:00': 358,
 '2000-01-15 23:00:00': 359,
 '2000-01-16 00:00:00': 360,
 '2000-01-16 01:00:00': 361,
 '2000-01-16 02:00:00': 362,
 '2000-01-16 03:00:00': 363,
 '2000-01-16 04:00:00': 364,
 '2000-01-16 05:00:00': 365,
 '2000-01-16 06:00:00': 366,
 '2000-01-16 07:00:00': 367,
 '2000-01-16 08:00:00': 368,
 '2000-01-16 09:00:00': 369,
 '2000-01-16 10:00:00': 370,
 '2000-01-16 11:00:00': 371,
 '2000-01-16 12:00:00': 372,
 '2000-01-16 13:00:00': 373,
 '2000-01-16 14:00:00': 374,
 '2000-01-16 15:00:00': 375,
 '2000-01-16 16:00:00': 376,
 '2000-01-16 17:00:00': 377,
 '2000-01-16 18:00:00': 378,
 '2000-01-16 19:00:00': 379,
 '2000-01-16 20:00:00': 380,
 '2000-01-16 21:00:00': 381,
 '2000-01-16 22:00:00': 382,
 '2000-01-16 23:00:00': 383,
 '2000-01-17 00:00:00': 384,
 '2000-01-17 01:00:00': 385,
 '2000-01-17 02:00:00': 386,
 '2000-01-17 03:00:00': 387,
 '2000-01-17 04:00:00': 388,
 '2000-01-17 05:00:00': 389,
 '2000-01-17 06:00:00': 390,
 '2000-01-17 07:00:00': 391,
 '2000-01-17 08:00:00': 392,
 '2000-01-17 09:00:00': 393,
 '2000-01-17 10:00:00': 394,
 '2000-01-17 11:00:00': 395,
 '2000-01-17 12:00:00': 396,
 '2000-01-17 13:00:00': 397,
 '2000-01-17 14:00:00': 398,
 '2000-01-17 15:00:00': 399,
 '2000-01-17 16:00:00': 400,
 '2000-01-17 17:00:00': 401,
 '2000-01-17 18:00:00': 402,
 '2000-01-17 19:00:00': 403,
 '2000-01-17 20:00:00': 404,
 '2000-01-17 21:00:00': 405,
 '2000-01-17 22:00:00': 406,
 '2000-01-17 23:00:00': 407,
 '2000-01-18 00:00:00': 408,
 '2000-01-18 01:00:00': 409,
 '2000-01-18 02:00:00': 410,
 '2000-01-18 03:00:00': 411,
 '2000-01-18 04:00:00': 412,
 '2000-01-18 05:00:00': 413,
 '2000-01-18 06:00:00': 414,
 '2000-01-18 07:00:00': 415,
 '2000-01-18 08:00:00': 416,
 '2000-01-18 09:00:00': 417,
 '2000-01-18 10:00:00': 418,
 '2000-01-18 11:00:00': 419,
 '2000-01-18 12:00:00': 420,
 '2000-01-18 13:00:00': 421,
 '2000-01-18 14:00:00': 422,
 '2000-01-18 15:00:00': 423,
 '2000-01-18 16:00:00': 424,
 '2000-01-18 17:00:00': 425,
 '2000-01-18 18:00:00': 426,
 '2000-01-18 19:00:00': 427,
 '2000-01-18 20:00:00': 428,
 '2000-01-18 21:00:00': 429,
 '2000-01-18 22:00:00': 430,
 '2000-01-18 23:00:00': 431,
 '2000-01-19 00:00:00': 432,
 '2000-01-19 01:00:00': 433,
 '2000-01-19 02:00:00': 434,
 '2000-01-19 03:00:00': 435,
 '2000-01-19 04:00:00': 436,
 '2000-01-19 05:00:00': 437,
 '2000-01-19 06:00:00': 438,
 '2000-01-19 07:00:00': 439,
 '2000-01-19 08:00:00': 440,
 '2000-01-19 09:00:00': 441,
 '2000-01-19 10:00:00': 442,
 '2000-01-19 11:00:00': 443,
 '2000-01-19 12:00:00': 444,
 '2000-01-19 13:00:00': 445,
 '2000-01-19 14:00:00': 446,
 '2000-01-19 15:00:00': 447,
 '2000-01-19 16:00:00': 448,
 '2000-01-19 17:00:00': 449,
 '2000-01-19 18:00:00': 450,
 '2000-01-19 19:00:00': 451,
 '2000-01-19 20:00:00': 452,
 '2000-01-19 21:00:00': 453,
 '2000-01-19 22:00:00': 454,
 '2000-01-19 23:00:00': 455,
 '2000-01-20 00:00:00': 456,
 '2000-01-20 01:00:00': 457,
 '2000-01-20 02:00:00': 458,
 '2000-01-20 03:00:00': 459,
 '2000-01-20 04:00:00': 460,
 '2000-01-20 05:00:00': 461,
 '2000-01-20 06:00:00': 462,
 '2000-01-20 07:00:00': 463,
 '2000-01-20 08:00:00': 464,
 '2000-01-20 09:00:00': 465,
 '2000-01-20 10:00:00': 466,
 '2000-01-20 11:00:00': 467,
 '2000-01-20 12:00:00': 468,
 '2000-01-20 13:00:00': 469,
 '2000-01-20 14:00:00': 470,
 '2000-01-20 15:00:00': 471,
 '2000-01-20 16:00:00': 472,
 '2000-01-20 17:00:00': 473,
 '2000-01-20 18:00:00': 474,
 '2000-01-20 19:00:00': 475,
 '2000-01-20 20:00:00': 476,
 '2000-01-20 21:00:00': 477,
 '2000-01-20 22:00:00': 478,
 '2000-01-20 23:00:00': 479,
 '2000-01-21 00:00:00': 480,
 '2000-01-21 01:00:00': 481,
 '2000-01-21 02:00:00': 482,
 '2000-01-21 03:00:00': 483,
 '2000-01-21 04:00:00': 484,
 '2000-01-21 05:00:00': 485,
 '2000-01-21 06:00:00': 486,
 '2000-01-21 07:00:00': 487,
 '2000-01-21 08:00:00': 488,
 '2000-01-21 09:00:00': 489,
 '2000-01-21 10:00:00': 490,
 '2000-01-21 11:00:00': 491,
 '2000-01-21 12:00:00': 492,
 '2000-01-21 13:00:00': 493,
 '2000-01-21 14:00:00': 494,
 '2000-01-21 15:00:00': 495,
 '2000-01-21 16:00:00': 496,
 '2000-01-21 17:00:00': 497,
 '2000-01-21 18:00:00': 498,
 '2000-01-21 19:00:00': 499,
 '2000-01-21 20:00:00': 500,
 '2000-01-21 21:00:00': 501,
 '2000-01-21 22:00:00': 502,
 '2000-01-21 23:00:00': 503,
 '2000-01-22 00:00:00': 504,
 '2000-01-22 01:00:00': 505,
 '2000-01-22 02:00:00': 506,
 '2000-01-22 03:00:00': 507,
 '2000-01-22 04:00:00': 508,
 '2000-01-22 05:00:00': 509,
 '2000-01-22 06:00:00': 510,
 '2000-01-22 07:00:00': 511,
 '2000-01-22 08:00:00': 512,
 '2000-01-22 09:00:00': 513,
 '2000-01-22 10:00:00': 514,
 '2000-01-22 11:00:00': 515,
 '2000-01-22 12:00:00': 516,
 '2000-01-22 13:00:00': 517,
 '2000-01-22 14:00:00': 518,
 '2000-01-22 15:00:00': 519,
 '2000-01-22 16:00:00': 520,
 '2000-01-22 17:00:00': 521,
 '2000-01-22 18:00:00': 522,
 '2000-01-22 19:00:00': 523,
 '2000-01-22 20:00:00': 524,
 '2000-01-22 21:00:00': 525,
 '2000-01-22 22:00:00': 526,
 '2000-01-22 23:00:00': 527,
 '2000-01-23 00:00:00': 528,
 '2000-01-23 01:00:00': 529,
 '2000-01-23 02:00:00': 530,
 '2000-01-23 03:00:00': 531,
 '2000-01-23 04:00:00': 532,
 '2000-01-23 05:00:00': 533,
 '2000-01-23 06:00:00': 534,
 '2000-01-23 07:00:00': 535,
 '2000-01-23 08:00:00': 536,
 '2000-01-23 09:00:00': 537,
 '2000-01-23 10:00:00': 538,
 '2000-01-23 11:00:00': 539,
 '2000-01-23 12:00:00': 540,
 '2000-01-23 13:00:00': 541,
 '2000-01-23 14:00:00': 542,
 '2000-01-23 15:00:00': 543,
 '2000-01-23 16:00:00': 544,
 '2000-01-23 17:00:00': 545,
 '2000-01-23 18:00:00': 546,
 '2000-01-23 19:00:00': 547,
 '2000-01-23 20:00:00': 548,
 '2000-01-23 21:00:00': 549,
 '2000-01-23 22:00:00': 550,
 '2000-01-23 23:00:00': 551,
 '2000-01-24 00:00:00': 552,
 '2000-01-24 01:00:00': 553,
 '2000-01-24 02:00:00': 554,
 '2000-01-24 03:00:00': 555,
 '2000-01-24 04:00:00': 556,
 '2000-01-24 05:00:00': 557,
 '2000-01-24 06:00:00': 558,
 '2000-01-24 07:00:00': 559,
 '2000-01-24 08:00:00': 560,
 '2000-01-24 09:00:00': 561,
 '2000-01-24 10:00:00': 562,
 '2000-01-24 11:00:00': 563,
 '2000-01-24 12:00:00': 564,
 '2000-01-24 13:00:00': 565,
 '2000-01-24 14:00:00': 566,
 '2000-01-24 15:00:00': 567,
 '2000-01-24 16:00:00': 568,
 '2000-01-24 17:00:00': 569,
 '2000-01-24 18:00:00': 570,
 '2000-01-24 19:00:00': 571,
 '2000-01-24 20:00:00': 572,
 '2000-01-24 21:00:00': 573,
 '2000-01-24 22:00:00': 574,
 '2000-01-24 23:00:00': 575,
 '2000-01-25 00:00:00': 576,
 '2000-01-25 01:00:00': 577,
 '2000-01-25 02:00:00': 578,
 '2000-01-25 03:00:00': 579,
 '2000-01-25 04:00:00': 580,
 '2000-01-25 05:00:00': 581,
 '2000-01-25 06:00:00': 582,
 '2000-01-25 07:00:00': 583,
 '2000-01-25 08:00:00': 584,
 '2000-01-25 09:00:00': 585,
 '2000-01-25 10:00:00': 586,
 '2000-01-25 11:00:00': 587,
 '2000-01-25 12:00:00': 588,
 '2000-01-25 13:00:00': 589,
 '2000-01-25 14:00:00': 590,
 '2000-01-25 15:00:00': 591,
 '2000-01-25 16:00:00': 592,
 '2000-01-25 17:00:00': 593,
 '2000-01-25 18:00:00': 594,
 '2000-01-25 19:00:00': 595,
 '2000-01-25 20:00:00': 596,
 '2000-01-25 21:00:00': 597,
 '2000-01-25 22:00:00': 598,
 '2000-01-25 23:00:00': 599,
 '2000-01-26 00:00:00': 600,
 '2000-01-26 01:00:00': 601,
 '2000-01-26 02:00:00': 602,
 '2000-01-26 03:00:00': 603,
 '2000-01-26 04:00:00': 604,
 '2000-01-26 05:00:00': 605,
 '2000-01-26 06:00:00': 606,
 '2000-01-26 07:00:00': 607,
 '2000-01-26 08:00:00': 608,
 '2000-01-26 09:00:00': 609,
 '2000-01-26 10:00:00': 610,
 '2000-01-26 11:00:00': 611,
 '2000-01-26 12:00:00': 612,
 '2000-01-26 13:00:00': 613,
 '2000-01-26 14:00:00': 614,
 '2000-01-26 15:00:00': 615,
 '2000-01-26 16:00:00': 616,
 '2000-01-26 17:00:00': 617,
 '2000-01-26 18:00:00': 618,
 '2000-01-26 19:00:00': 619,
 '2000-01-26 20:00:00': 620,
 '2000-01-26 21:00:00': 621,
 '2000-01-26 22:00:00': 622,
 '2000-01-26 23:00:00': 623,
 '2000-01-27 00:00:00': 624,
 '2000-01-27 01:00:00': 625,
 '2000-01-27 02:00:00': 626,
 '2000-01-27 03:00:00': 627,
 '2000-01-27 04:00:00': 628,
 '2000-01-27 05:00:00': 629,
 '2000-01-27 06:00:00': 630,
 '2000-01-27 07:00:00': 631,
 '2000-01-27 08:00:00': 632,
 '2000-01-27 09:00:00': 633,
 '2000-01-27 10:00:00': 634,
 '2000-01-27 11:00:00': 635,
 '2000-01-27 12:00:00': 636,
 '2000-01-27 13:00:00': 637,
 '2000-01-27 14:00:00': 638,
 '2000-01-27 15:00:00': 639,
 '2000-01-27 16:00:00': 640,
 '2000-01-27 17:00:00': 641,
 '2000-01-27 18:00:00': 642,
 '2000-01-27 19:00:00': 643,
 '2000-01-27 20:00:00': 644,
 '2000-01-27 21:00:00': 645,
 '2000-01-27 22:00:00': 646,
 '2000-01-27 23:00:00': 647,
 '2000-01-28 00:00:00': 648,
 '2000-01-28 01:00:00': 649,
 '2000-01-28 02:00:00': 650,
 '2000-01-28 03:00:00': 651,
 '2000-01-28 04:00:00': 652,
 '2000-01-28 05:00:00': 653,
 '2000-01-28 06:00:00': 654,
 '2000-01-28 07:00:00': 655,
 '2000-01-28 08:00:00': 656,
 '2000-01-28 09:00:00': 657,
 '2000-01-28 10:00:00': 658,
 '2000-01-28 11:00:00': 659,
 '2000-01-28 12:00:00': 660,
 '2000-01-28 13:00:00': 661,
 '2000-01-28 14:00:00': 662,
 '2000-01-28 15:00:00': 663,
 '2000-01-28 16:00:00': 664,
 '2000-01-28 17:00:00': 665,
 '2000-01-28 18:00:00': 666,
 '2000-01-28 19:00:00': 667,
 '2000-01-28 20:00:00': 668,
 '2000-01-28 21:00:00': 669,
 '2000-01-28 22:00:00': 670,
 '2000-01-28 23:00:00': 671,
 '2000-01-29 00:00:00': 672,
 '2000-01-29 01:00:00': 673,
 '2000-01-29 02:00:00': 674,
 '2000-01-29 03:00:00': 675,
 '2000-01-29 04:00:00': 676,
 '2000-01-29 05:00:00': 677,
 '2000-01-29 06:00:00': 678,
 '2000-01-29 07:00:00': 679,
 '2000-01-29 08:00:00': 680,
 '2000-01-29 09:00:00': 681,
 '2000-01-29 10:00:00': 682,
 '2000-01-29 11:00:00': 683,
 '2000-01-29 12:00:00': 684,
 '2000-01-29 13:00:00': 685,
 '2000-01-29 14:00:00': 686,
 '2000-01-29 15:00:00': 687,
 '2000-01-29 16:00:00': 688,
 '2000-01-29 17:00:00': 689,
 '2000-01-29 18:00:00': 690,
 '2000-01-29 19:00:00': 691,
 '2000-01-29 20:00:00': 692,

In [33]:
us_filtered_df['DATETIME'] = us_filtered_df['DATETIME'].apply(lambda x : datetime_dict[str(x)])
us_filtered_df['END_DATETIME'] = us_filtered_df['END_DATETIME'].apply(lambda x : datetime_dict[str(x)])
us_filtered_df

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_DAY,END_TIME,END_YEARMONTH,LAT,LON,DATETIME,END_DATETIME
349109,200008,03,1410,03,1410,200008,1.0,4.0,5174,5174
349110,200008,09,1405,09,1405,200008,1.0,4.0,5318,5318
349111,200008,09,1615,09,1615,200008,1.0,4.0,5320,5320
349124,200002,13,2310,13,2310,200002,2.0,3.0,1055,1055
349125,200002,13,2315,13,2315,200002,2.0,3.0,1055,1055
...,...,...,...,...,...,...,...,...,...,...
1531617,201903,03,1913,03,1916,201903,2.0,3.0,168043,168043
1531618,201903,03,1853,03,1906,201903,2.0,3.0,168042,168043
1531619,201903,03,1913,03,1916,201903,2.0,3.0,168043,168043
1531620,201903,03,1933,03,1935,201903,2.0,3.0,168043,168043
1531621,201903,01,1915,01,1915,201903,2.0,3.0,167995,167995

# Creating Output Memmap with Storms

Create np array with proper shape for training, the size depends on whether we start at 1979 (359400) and 2000 (175320)

In [ ]:
storm_np = np.zeros((359400, 1, 5, 12))

In [34]:
storm_np = np.zeros((175320, 1, 5, 12))

Two separate methods for filling out the Memmap, one adds a single value for storm values and the other adds for ongoing storms, the benefits and downsides of both are described in our paper

In [ ]:
for index, row in us_filtered_df.iterrows():
    storm_np[int(row['DATETIME']), 0, int(row['LAT']), int(row['LON'])] += 1

In [ ]:
for index, row in us_filtered_df.iterrows():
  for i in np.arange(int(row['DATETIME']), int(row['END_DATETIME'])):
    if i >= 175320:
      break
    storm_np[i, 0, int(row['LAT']), int(row['LON'])] += 1

In [ ]:
storm_np.sum()

2813833.0

Create a memmap using the filled out storm_np

In [ ]:
storm_data_memmap = np.memmap('storm_data_us_flood_2000.mmap', dtype='float32', mode='w+', shape=(175320, 1, 5, 12))
storm_data_memmap[:] = storm_np